apiVersion: v1
data:
  apiToken: ENC[AES256_GCM,data:IS9v35Tm/C93ewe7PFid5Wwt/OIQf8xRuXeDtS9EMll6kMdbkgCMIyU/VmdFAJbeXreRLU2jZ3BhL/TAMAGfjZqddD2IxgVotkVwmeB/7dlP8i/0Ntn1YkPzG4+MRelBBE7FyJxWgD9VzWF/9QzcTbShQIq8Bsv/8lGhjvZ/K+E=,iv:89lyGQlP8fFOJ3bemRZ5nQoBCR3MBwsNN+NXc9RPx5E=,tag:G94uvlMIsq/76lB8igo0aA==,type:str]
  dataIngestToken: ENC[AES256_GCM,data:x5nM+S9HoUX90zgem7MYGF+zDr5P1vm+R7tTaNxKNeA2j/806FMj68kGEnhA0SiVwdbm3iBFq7rV5SpN1NhhaNByWXxsX6Dag0wEORVQLBb+bgIrmj4RRVT4b1S2o3oA29OhQvoF6LkR7snwDVomzGelqKBaHNpz8iM3vs33jDI=,iv:pWwtoySlvArCyHknv3KyFzeXeYJGlrJHYP+HXCAIGv4=,tag:LN1MPCwt9lfTX1OsomhaXg==,type:str]
kind: Secret
metadata:
  name: dynakube
  namespace: dynatrace
type: Opaque
sops:
  azure_kv:
    - created_at: "2023-02-01T11:12:03Z"
      enc: fhiMyEGmlzKCrkauKnTgiTp4KPKEO4hOTH8MPdFEOJ-koxJuWcVmhaYss6UPM005fvJEjHfCaRKvEMzzrab0lFf6W8mpM2OPRcjkb3PyEshjAWRsthK1-_wb-3vNpCtLZ5QeXTjUKySbCJXrKOj9nqyxPZx5LY90h-nZIqU8eFYgsM7C5dkh-IGXuV2m_PgO5-OofPSPxhugUqPmWfr2104J8Htxn_2JOWWbv7oOJKfCoeUJtXZc5DpW-5bmkW8ifyl7l7ogC6NCkCaefgCEJ079tEa1O6mrPTT7fCZ_nnPYSP-_E2uQq3pfiajeruk7SBMF_y3pf3k94IqyKSyO4g
      name: sops-key
      vault_url: https://dtssharedservicesstgkv.vault.azure.net
      version: b63a642ce6b14537bcc33a500f90b0e9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T14:42:50Z"
  mac: ENC[AES256_GCM,data:mOSuQI3JZcTykdAXg5o1G0rm+M1TM88B43im9xtcCRfmFBbEWjKO44nCino5nLV+ZCW+9x549Ty96FgTgvPakdxXU4YqSrTEL73yXDtrc6NqeIK5S/mIqhv6IiVROXMfovtyViAm2L/aIakhrXt71wa0aaSapBWhyVWb722pai4=,iv:EBaACByni4xUT62tfvh9x3Z4ZiHZCPWvHhFgi30svPI=,tag:g3tYkJ6uTJ9KCnRxSrFxxA==,type:str]
  version: 3.13.3
