apiVersion: dbforpostgresql.azure.com/v20250801
kind: FlexibleServer
metadata:
  name: ${NAMESPACE}-${ENVIRONMENT}
  namespace: ${NAMESPACE}
spec:
  sku:
    name: Standard_D2ds_v5
    tier: GeneralPurpose
