apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juror-scheduler-api
  namespace: juror
spec:
  releaseName: juror-scheduler-api
  values:
    java:
      # Uncomment and edit the line below to fix the environment at a specific image
      # image: hmctsprod.azurecr.io/juror/scheduler-api:prod-24c3947-20251023133823 # {"$imagepolicy": "flux-system:juror-scheduler-api-pr"}
      ingressHost: juror-scheduler-api.demo.platform.hmcts.net
