apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juror-scheduler-api
  namespace: juror
spec:
  releaseName: juror-scheduler-api
  values:
    java:
      # Uncomment and edit the line below to fix the environment at a specific image
      image: hmctsprod.azurecr.io/juror/scheduler-api:pr-313-014d46e-20260923123507 # {"$imagepolicy": "flux-system:juror-scheduler-api-pr"}
      ingressHost: juror-scheduler-api.ithc.platform.hmcts.net
