apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - ../../identity/cath-azure-identity.yaml
  - ../../../rbac/dev-role.yaml
  - ../../../base/workload-identity
  - ../../../base/slack-provider/dev
  - ../../../azureserviceoperator-system/resources/resource-group.yaml
namespace: cath
patches:
  - path: ../../identity/dev.yaml
  - path: ../../serviceaccount/stg.yaml
