apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pre-api-cron-check-for-missing-recordings
  namespace: pre
spec:
  values:
    global:
      jobKind: CronJob
    job:
      schedule: "15 6 * * *" # 6:15 AM UTC
      image: hmctsprod.azurecr.io/pre/api:prod-41d5a16-20260304171000 # {"$imagepolicy": "flux-system:pre-api"}
