apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pre-api-cron-check-for-missing-recordings
  namespace: pre
spec:
  values:
    global:
      jobKind: CronJob
    job:
      schedule: "15 19 * * *" # 7:15 PM UTC
      image: hmctsprod.azurecr.io/pre/api:staging-2212602-20260424083114 # {"$imagepolicy": "flux-system:stg-pre-api"}
      environment:
        PLATFORM_ENV_TAG: Staging
