apiVersion: dbforpostgresql.azure.com/v20250801
kind: FlexibleServersConfiguration
metadata:
  name: maxconnections
  namespace: ${NAMESPACE}
  annotations:
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
spec:
  owner:
    name: ${NAMESPACE}-${ENVIRONMENT}
  azureName: max_connections
  source: user-override
  value: "5000"
