apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../cath-web/cath-web.yaml
  - ../../cath-api/cath-api.yaml
  - ../../cath-crons/cath-crons.yaml
  - ../../cath-postgres/cath-postgres.yaml
  - ../../../base/slack-provider/stg
namespace: cath
patches:
  - path: ../../identity/stg.yaml
  - path: ../../cath-web/stg.yaml
  - path: ../../cath-api/stg.yaml
  - path: ../../cath-crons/stg.yaml
  - path: ../../cath-postgres/stg.yaml
  - path: ../../serviceaccount/stg.yaml
