apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-frontend
  namespace: opal
spec:
  releaseName: opal-frontend
  values:
    nodejs:
      image: hmctsprod.azurecr.io/opal/frontend:pr-2877-9aeb56e-20260709083204 # {"$imagepolicy": "flux-system:opal-frontend-pr"}
      enabled: true
      ingressHost: opal-frontend.test.apps.hmcts.net
      environment:
        DUMMY_VAR: 1
        FRONTEND_HOSTNAME: https://opal-frontend.test.apps.hmcts.net
        OPAL_API_URL: https://opal-fines-service.test.platform.hmcts.net
        OPAL_FINES_SERVICE_API_URL: https://opal-fines-service.test.platform.hmcts.net
        OPAL_USER_SERVICE_API_URL: https://opal-user-service.test.platform.hmcts.net
