apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-logging-service
  namespace: opal
spec:
  releaseName: opal-logging-service
  values:
    java:
      image: hmctsprod.azurecr.io/opal/logging-service:pr-200-029bd14-20260616123230 # {"$imagepolicy": "flux-system:opal-logging-service-pr"}
      ingressHost: opal-logging-service.test.platform.hmcts.net
      environment:
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/perfTest
