apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-logging-service
  namespace: opal
spec:
  releaseName: opal-logging-service
  values:
    java:
      ingressHost: opal-logging-service.test.platform.hmcts.net
      image: hmctsprod.azurecr.io/opal/logging-service:pr-157
      environment:
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/perfTest
