apiVersion: v1
data:
  apiToken: ENC[AES256_GCM,data:bDSbnFWJj2jDmkthLvzd5KZKDitPvMh1OKFAGZ2VZOm7TazrzHtg+ZE4y5ITbN3+sMEj5abA+9PMMdeRh1OwSqR0JUwu1w+Vm8Ad0tu7YH2BUSRiBW4ChS68KUpLec12JZ5t5l9CF+G4Lo1q3bKGSfutkW6I2V5FWSgC5PDQXg/UtQ==,iv:kycRIwKM8MUnQcMS9A2e0cKPdiJ9lNvVvh1olHJBhPM=,tag:CvxkGN2uZCdJl9JOLLaquw==,type:str]
  dataIngestToken: ENC[AES256_GCM,data:mnt9fOdXQ6lbE3hM4W5des3zFMVsqAUSxFGVaIrvLgULPI8Q0aBDht4Q9hobRwBqlLpc90onLqSS2aIEmG+BrhpyAT2Av5veAGkRnbpxlZpb51v0xuX7ITOvInsIRirYv9ElvHMWM0MVgTTeCwUoCtfOsNRz+QDXNOscQSSeeU/lKg==,iv:YyImvkhQkBJi8Tc/58UTypp0UvpmMNCHx00+h7xMEME=,tag:PCDaYWJL8zVqzkuX/4oErw==,type:str]
kind: Secret
metadata:
  name: dynakube
  namespace: dynatrace
type: Opaque
sops:
  azure_kv:
    - created_at: "2023-02-01T11:14:48Z"
      enc: be2DlwBu0REtEnApW5m_DDu7STKTQ5qsGOdH2lM7VkfqOP3eu-BVmvtg-5Fj5QTX02pN5-xpxWZmBN2M9lwKkRdE_VwYKuICorU2FDCoAI9S_cLDOGSytHd2oFTyG8dQIiJ3FQPzZHozMtlzjIiBfNuU3mTwmHTRINearTYCYoz8rKC5lQrzkMcXqwyuRRyWrdc1cyBPJ4Rs1rfuezipR_Ns2ryjLQI9o6Mkf18tUJAxyeXC5DE973NU0WAMQQrWx8uJJYqPTCXYMqVKaQpW_XAPHCGXm-smO5eiWt0W-QaSPKGPtHZThpAXkrloVjHn76dyGSaC1-YEW6clrHIfcg
      name: sops-key
      vault_url: https://dtssharedservicesprodkv.vault.azure.net
      version: 883d8b431ad345d09b2697c3aaae2a0c
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T15:31:11Z"
  mac: ENC[AES256_GCM,data:81aOCGW+wcM04jhFNPVQvSc6drXQuAPHdiHACIdFoGR0Ad7WlndBNF7S3u0OGg6/GEZZvTWDno+zwdOpxQkj9Q/a4Nnzs8a/ZWX25UO5y/2EvG55duHFpP8kmmhcIrBrvKYYmTEuSTdEqa2jN2OVPcHGLnZUTXv6oiNx9FTeYtA=,iv:l2xU1nA6zmDuF9owbvpUqd+VWtWtGGAi+ixDmYJDCBQ=,tag:KgohrVEGXVjxqrlh2hELYw==,type:str]
  version: 3.13.3
