---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  values:
    controller:
      JCasC:
        configScripts:
          azure-vm-agent: |
            x-vmTemplate-values: &vm_template_values_anchor
              launcher: "ssh"
              agentWorkspace: "/opt/jenkins"
              builtInImage: "Windows Server 2016"
              credentialsId: "vm_agent_creds"
              diskType: "managed"
              doNotUseMachineIfInitFails: true
              enableUAMI: true
              ephemeralOSDisk: true
              executeInitScriptAsRoot: true
              existingStorageAccountName: "hmctsjenkinssds"
              imageTopLevelType: "advanced"
              initScript: |
                usermod -a -G docker jenkinsssh
                usermod -a -G rvm jenkinsssh
                umount /mnt/resource
                mkdir -pv /opt/jenkins
                mount /dev/sdb1 /opt/jenkins
                chown -R jenkinsssh:jenkinsssh /opt/jenkins
                set -e
                cp /opt/jenkinsssh_id_rsa /home/jenkinsssh/.ssh/id_rsa
                chown jenkinsssh:jenkinsssh /home/jenkinsssh/.ssh/id_rsa
                chmod 0600 /home/jenkinsssh/.ssh/id_rsa
                mkdir /opt/jenkins/.gradle && echo 'org.gradle.daemon=false' > /opt/jenkins/.gradle/gradle.properties
                cat > /etc/security/limits.d/30-jenkins.conf<<EOF
                jenkinsssh soft nofile 40960
                jenkinsssh hard nofile 40960
                jenkinsssh soft
                proc 32768
                jenkinsssh hard nproc 32768
                jenkinsssh soft core unlimited
                jenkinsssh hard core unlimited
                EOF
                ssh-keyscan github.com github.com >> /home/jenkinsssh/.ssh/known_hosts
                ssh-keygen -F github.com -f /home/jenkinsssh/.ssh/known_hosts # verifies key is correctly installed
                chown jenkinsssh:jenkinsssh /home/jenkinsssh/.ssh/known_hosts
              installDocker: false
              installGit: false
              installMaven: false
              javaPath: /usr/lib/jvm/temurin-21-jdk-amd64/bin/java
              jvmOptions: "-Xms4G -Xmx6G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers\
            \ -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled\
            \ -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions\
            \ -XX:G1SummarizeRSetStatsPeriod=1"
              location: "UK South"
              noOfParallelJobs: 1
              osDiskSize: 60
              osDiskStorageAccountType: "Standard_LRS"
              osType: "Linux"
              storageAccountNameReferenceType: "existing"
              storageAccountType: "Standard_LRS"
              subnetName: "iaas"
              uamiID: /subscriptions/6c4d2513-a873-41b4-afdd-b05a33206631/resourceGroups/managed-identities-ptl-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-ptl-mi
              usePrivateIP: true
              virtualNetworkName: "ss-ptl-vnet"
              virtualNetworkResourceGroupName: "ss-ptl-network-rg"
            jenkins:
              clouds:
                - azureVM:
                    cloudTags:
                      - name: "application"
                        value: "core"
                      - name: "builtFrom"
                        value: "hmcts/sds-flux-config"
                      - name: "businessArea"
                        value: "Cross-Cutting"
                      - name: "criticality"
                        value: "High"
                      - name: "environment"
                        value: "production"
                    azureCredentialsId: "jenkins-managed-identity"
                    name: "cnp-azure"
                    deploymentTimeout: 1200
                    newResourceGroupName: "vm-agents-rg"
                    resourceGroupReferenceType: "new"
                    maxVirtualMachinesLimit: 0
                    vmTemplates:
                    - templateName: "cnp-jenkins-builders"
                      templateDesc: "Jenkins build agents for HMCTS"
                      labels: "daily"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 40
                      usageMode: "NORMAL"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-dev"
                      templateDesc: "Jenkins build agents for SDS dev environment"
                      labels: "ubuntu-dev"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/867a878b-cb68-4de5-9741-361ac9e178b6/resourceGroups/managed-identities-dev-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-dev-mi
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-stg"
                      templateDesc: "Jenkins build agents for SDS stg environment"
                      labels: "ubuntu-stg"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/74dacd4f-a248-45bb-a2f0-af700dc4cf68/resourceGroups/managed-identities-stg-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-stg-mi
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-ithc"
                      templateDesc: "Jenkins build agents for SDS ithc environment"
                      labels: "ubuntu-ithc"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/ba71a911-e0d6-4776-a1a6-079af1df7139/resourceGroups/managed-identities-ithc-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-ithc-mi
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-test"
                      templateDesc: "Jenkins build agents for SDS test environment"
                      labels: "ubuntu-test"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/3eec5bde-7feb-4566-bfb6-805df6e10b90/resourceGroups/managed-identities-test-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-test-mi
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-demo"
                      templateDesc: "Jenkins build agents for SDS demo environment"
                      labels: "ubuntu-demo"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/c68a4bed-4c3d-4956-af51-4ae164c1957c/resourceGroups/managed-identities-demo-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-demo-mi
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-prod"
                      templateDesc: "Jenkins build agents for SDS prod environment"
                      labels: "ubuntu-prod"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/resourceGroups/managed-identities-prod-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-prod-mi
                      <<: *vm_template_values_anchor
                    - templateName: "cnp-jenkins-builders-ptl"
                      templateDesc: "Jenkins build agents for SDS ptl environment"
                      labels: "ubuntu-ptl"
                      retentionStrategy:
                        azureVMCloudRetentionStrategy:
                          idleTerminationMinutes: 5
                      maxVirtualMachinesLimit: 10
                      usageMode: "EXCLUSIVE"
                      virtualMachineSize: "Standard_D4ds_v5"
                      imageReference:
                        galleryImageDefinition: "jenkins-ubuntu-v2"
                        galleryImageVersion: "24.04.79"
                        galleryName: "hmcts"
                        galleryResourceGroup: "hmcts-image-gallery-rg"
                        gallerySubscriptionId: "2b1afc19-5ca9-4796-a56f-574a58670244"
                      uamiID: /subscriptions/6c4d2513-a873-41b4-afdd-b05a33206631/resourceGroups/managed-identities-ptl-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-ptl-mi
                      <<: *vm_template_values_anchor
