apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juror-bureau
  namespace: juror
spec:
  releaseName: juror-bureau
  values:
    nodejs:
      # Uncomment and edit the line below to fix the environment at a specific image
      image: hmctsprod.azurecr.io/juror/bureau:pr-1198-2b1dabf-20260615121741 # {"$imagepolicy": "flux-system:juror-bureau-test"}
      ingressHost: juror.test.apps.hmcts.net
      environment:
        SKIP_SSO: true
        RESTART: 1
