kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-team-permissions
rules:
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['']
  resources: ['secrets']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['helm.toolkit.fluxcd.io']
  resources: ['helmreleases']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['']
  resources: ['pods/exec']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['']
  resources: ['pods/portforward']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['']
  resources: ['services']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['apps']
  resources: ['deployments']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['policy']
  resources: ['poddisruptionbudgets']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['networking.k8s.io']
  resources: ['ingresses']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['']
  resources: ['serviceaccounts']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['batch']
  resources: ['cronjobs']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
- apiGroups: ['keda.sh']
  resources: ['scaledjobs', 'scaledobjects', 'triggerauthentications']
  verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete', 'deletecollection']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-team-permissions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-team-permissions
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "${TEAM_AAD_GROUP_ID:=7bde62e7-b39f-487c-95c9-b4c794fdbb96}"
