apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-postgres
spec:
  releaseName: cath-postgres
  values:
    nodejs:
      image: hmctspublic.azurecr.io/cath/cath-postgres:prod-885d1dd-20260612144303 # {"$imagepolicy": "flux-system:cath-postgres"}
      disableTraefikTls: true
  chart:
    spec:
      chart: cath-postgres
      version: ">=0.0.1-0"
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci # correct
        namespace: flux-system
      interval: 1m
  install:
    disableWait: true
  upgrade:
    disableWait: true
