apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-fines-service
  namespace: opal
spec:
  releaseName: opal-fines-service
  values:
    java:
      ingressHost: opal-fines-service.ithc.platform.hmcts.net
      image: hmctsprod.azurecr.io/opal/fines-service:pr-1772
      environment:
        DUMMY_VAR: 0
        OPAL_FRONTEND_URL: https://opal-frontend.ithc.apps.hmcts.net
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/ithc
        OPAL_LEGACY_GATEWAY_URL: https://cloudgobgateway.test.platform.hmcts.net/opal
        DEFAULT_APP_MODE: legacy
