apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-fines-service
  namespace: opal
spec:
  releaseName: opal-fines-service
  values:
    java:
      ingressHost: opal-fines-service.platform.hmcts.net
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.apps.hmcts.net
        OPAL_USER_SERVICE_API_URL: https://opal-user-service.platform.hmcts.net
        OPAL_LEGACY_GATEWAY_URL: https://cloudgobgateway.platform.hmcts.net/opal
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
