apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: cath
  namespace: cath
spec:
  resourceID: /subscriptions/ba71a911-e0d6-4776-a1a6-079af1df7139/resourceGroups/managed-identities-ithc-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cath-ithc-mi
  clientID: 9e20ac3d-b819-4b6d-9f06-bd1a82e5a849
