apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: cath
  namespace: cath
spec:
  resourceID: /subscriptions/PLACEHOLDER/resourcegroups/managed-identities-prod-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cath-prod-mi
  clientID: PLACEHOLDER
