apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/stg/00
  postBuild:
    substitute:
      ENVIRONMENT: "stg"
      WI_ENVIRONMENT: "stg"
      CLUSTER: "00"
      ISSUER_URL: "https://uksouth.oic.prod-aks.azure.com/531ff96d-0ae9-462a-8d2d-bec7c0b42082/61603c44-c838-4d4d-bb5c-9e3a36b5143e/"
      ENV_MONITOR_CHANNEL: "aks-monitor-ss-stg"
      KEYVAULT_ENVIRONMENT: "stg"
      ACTIVE_CRON_CLUSTER: "true"