apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: appreg
patches:
  - path: ../../serviceaccount/prod.yaml
  - path: ../../appreg-api/prod.yaml
  - path: ../../appreg-frontend/prod.yaml
