apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toffee-recipe-backend
  namespace: toffee
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/toffee/recipe-backend:prod-1a3a1ef-20260723075257 #{"$imagepolicy": "flux-system:toffee-recipe-backend"}
      ingressHost: toffee-recipe-backend.platform.hmcts.net
      useWorkloadIdentity: true
      workloadClientID: ${WORKLOAD_IDENTITY_ID}
      autoscaling:
        enabled: true
        maxReplicas: 5 # Required setting
      environment:
        DUMMY_VAR: true
    global:
      environment: prod
