apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toffee-recipe-backend
  namespace: toffee
  annotations:
    fluxcd.io/automated: "false"
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/toffee/recipe-backend:prod-17b65d5-20260723081025 #{"$imagepolicy": "flux-system:toffee-recipe-backend"}
      ingressHost: toffee-recipe-backend.staging.platform.hmcts.net
      useWorkloadIdentity: true
      workloadClientID: ${WORKLOAD_IDENTITY_ID}
    global:
      environment: staging
