apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mi-azure-functions-deployment
  namespace: mi
spec:
  interval: 5m
  releaseName: mi-azure-functions
  values:
    image: hmctsprod.azurecr.io/mi/azure-functions:prod-18dccfc-20260521165748 #{"$imagepolicy": "flux-system:mi-azure-functions"}
    keyVaultSecrets:
      - encryption-publicKey
  chart:
    spec:
      chart: mi-azure-functions
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci
        namespace: flux-system
