apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pip-data-management-scheduled-subscriptions-cron
spec:
  releaseName: pip-data-management-scheduled-subscriptions-cron
  values:
    job:
      image: hmctsprod.azurecr.io/pip/data-management:pr-864-d1b2c27-20260326170708
      schedule: "40 13 * * 0,2,4,6"
      environment:
        DATA_MANAGEMENT_URL: https://pip-data-management.staging.platform.hmcts.net
        ACCOUNT_MANAGEMENT_URL: https://pip-account-management.staging.platform.hmcts.net
        TRIGGER_TYPE: SCHEDULED_LIST_TYPE_SUBSCRIPTIONS