apiVersion: v1
data:
  apiToken: ENC[AES256_GCM,data:2mW6lq5lYYlkv9zHcAgJtDaxDIHulRnBlK9Oplz1eswXNpEdsHVcfGVhq2/Qch8CEPIgQsiF2tlTKBJxzww5i3ZJPXF71ovmhlUKOSdRmpIT9s6JxXlLUXKOufA3cyo/CmlVYRVOj8q2e6+HWBqbNjrAnUeMJhMJLVktPSKy4Pw=,iv:qsSm+qPq8/Evf/YO8lwpYqhJDz6d5gaD24WpXQvQJRk=,tag:zRWxBIiDlBQVNgTJDQz8CQ==,type:str]
  dataIngestToken: ENC[AES256_GCM,data:dtdwJHiyRme1868a8EKO347wK4d84deAxo23lcl8quoHrjCnlEDj0wxnn1mHZw/iUXZq/oUCbIkNpIBCjXHwJUMZeBaKaE5WIjLCVKO6kXHw33URWVnAzE30W8/BYMt1ue7Dy0jy2KNzHjHoKi2dIW2yA+GbMP1XcTFml9b2CwQ=,iv:lwYMbWS4rVb5uSQgfAEOuUryzWn0QNF2XqIpOIYlGhk=,tag:+f481gNvwYLle3A0urIVmg==,type:str]
kind: Secret
metadata:
  name: dynakube
  namespace: dynatrace
type: Opaque
sops:
  azure_kv:
    - created_at: "2026-09-08T14:02:33Z"
      enc: TWvnK62Gx_Z5tjoQVKPSYPN1tWxcnDh5y9knBodiIuY6RMTPWioL4AAB14hF3sndEckNDmag2lrdPLxovhgz4oglkkU0aP1UVUwzTQVf8ieJkqG6xH_usrBWDPtVksXYSIfvqCCyE_pRcZa_D_Gvk5oRrthBDgdrSTCo1Z3eMzcnwzV1nNtCQgXQe-MVBDjZeymIyGce5CB6zBoyaejyCPUpjVaffRMg7T7SAkJTGPp7vXYkDyktNiSPWJRKL7JLSkgx_o8kP7JvDb0JjI_43XXbc5E9Dh8t_DkpMGFVcwHOT07bYR_IcT8dP0UNRdG216sc0_5BVCHKimEo0KKABg
      name: sops-key
      vault_url: https://dtssharedservicesdemokv.vault.azure.net
      version: 0657d01a616f4a0abb44e8b4ff26ac71
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T14:02:35Z"
  mac: ENC[AES256_GCM,data:HcWZA4zb+uF7IkLsZJIDCXGAebUdm0SEhqIUObgbRVrCS7LOhuzc1rh+p2GcexKBs7SJ9L3g5I7lr8NaVxAlyEX08Bcsg/4g4i+BqnhgSHNHuzwTghlB4RuVNwCvu2h0+92w60GnRi/wn1HkIc7WU4FOiUbBxf6/xIw4q1S8TxE=,iv:CROxVnJ6/PKzN9jcTK1Vnxap72cvbxK3q4Bg3GkGu6s=,tag:Gyp4MHaRjjYm6/mI7hZlkQ==,type:str]
  version: 3.13.3
