kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mi
  name: mi-developer
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "events", "limitranges", "persistentvolumeclaims", "pods", "pods/attach", "pods/ephemeralcontainers", "pods/exec", "pods/log", "pods/portforward", "pods/proxy", "pods/status", "replicationcontrollers", "replicationcontrollers/scale", "replicationcontrollers/status", "resourcequotas", "secrets", "serviceaccounts", "services", "services/proxy", "services/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["extensions"]
  resources: ["daemonsets", "deployments", "deployments/scale", "deployments/status", "ingresses", "ingresses/status", "networkpolicies", "replicasets", "replicasets/scale", "replicasets/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["apps"]
  resources: ["controllerrevisions", "daemonsets", "daemonsets/status", "deployments", "deployments/scale", "deployments/status", "replicasets", "replicasets/scale", "replicasets/status", "statefulsets", "statefulsets/scale", "statefulsets/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "cronjobs/status", "jobs", "jobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["helm.fluxcd.io", "helm.toolkit.fluxcd.io"]
  resources: ["helmreleases", "helmreleases/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureassignedidentities", "azureidentities", "azureidentitybindings", "azurepodidentityexceptions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mi-developer
  namespace: mi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mi-developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "686c38d0-706c-4851-b40d-b3fa18f2a8af"
