apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-rm-frontend
  namespace: opal
spec:
  releaseName: opal-rm-frontend
  chart:
    spec:
      chart: ./stable/opal-rm-frontend
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
  values:
    nodejs:
      image: hmctsprod.azurecr.io/opal/rm-frontend:prod-62ef50e-20260430145148 # {"$imagepolicy": "flux-system:opal-rm-frontend"}
      disableTraefikTls: true
