apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cath-crons
  annotations:
    hmcts.github.com/image-registry: hmctspublic
spec:
  image: hmctspublic.azurecr.io/cath/cath-crons
