apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-maintenance-service
  namespace: opal
spec:
  releaseName: opal-maintenance-service
  values:
    java:
      ingressHost: opal-maintenance-service.staging.platform.hmcts.net
