apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-file-handler-service
  namespace: opal
spec:
  releaseName: opal-file-handler-service
  chart:
    spec:
      chart: ./stable/opal-file-handler-service
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
  values:
    java:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
      disableTraefikTls: true
    bt-eckoh-report:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    caps-report:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    natwest-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    allpay-file-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    barclaycard-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    bt-eckoh-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    dwp-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    jacobs-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    cder-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
    marston-transfer:
      image: hmctsprod.azurecr.io/opal/file-handler-service:prod-98ff092-20260908091825 # {"$imagepolicy": "flux-system:opal-file-handler-service"}
