apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-file-handler-service
  namespace: opal
spec:
  releaseName: opal-file-handler-service
  values:
    java:
      ingressHost: opal-file-handler-service.test.platform.hmcts.net
      environment:
        DUMMY_VAR: 0
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/demo
    bt-eckoh-report:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    caps-report:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    natwest-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    allpay-file-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    barclaycard-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    bt-eckoh-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    dwp-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    jacobs-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    cder-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
    marston-transfer:
      enabled: true
      environment:
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        TESTING_SUPPORT_ENDPOINTS_ENABLED: false
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/test
