apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: darts-portal-ithc
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  imageRepositoryRef:
    name: darts-portal
  filterTags:
    extract: $ts
    pattern: '^pr-2330-[a-f0-9]+-(?P<ts>[0-9]+)'
  policy:
    alphabetical:
      order: asc
