apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: appreg-api
  namespace: appreg
spec:
  releaseName: appreg-api
  values:
    java:
      ingressHost: appreg-api.demo.platform.hmcts.net
      image: hmctsprod.azurecr.io/appreg/api:prod-27c566c-20260330130435 # {"$imagepolicy": "flux-system:appreg-api"}
      environment:
        ENV_NAME: "DEMO"
        LOG_LEVEL: "DEBUG"
