apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: appreg-api
  namespace: appreg
spec:
  releaseName: appreg-api
  values:
    java:
      ingressHost: appreg-api.ithc.platform.hmcts.net
      image: hmctsprod.azurecr.io/appreg/api:prod-2d8e657-20260811082631 # {"$imagepolicy": "flux-system:appreg-api"}
      environment:
        ENV_NAME: "ITHC"
        LOG_LEVEL: "DEBUG"
