apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: appreg-api
  namespace: appreg
spec:
  releaseName: appreg-api
  values:
    java:
      ingressHost: appreg-api.test.platform.hmcts.net
      image: hmctsprod.azurecr.io/appreg/api:prod-f49cd83-20260717144351 # {"$imagepolicy": "flux-system:appreg-api"}
      environment:
        ENV_NAME: "PERFTEST"
      keyVaults:
        appreg: null
        appreg-kv:
          secrets:
            - name: AppInsightsInstrumentationKey
              alias: APP_INSIGHTS_INSTRUMENTATION_KEY
            - name: app-insights-connection-string
              alias: app-insights-connection-string
            - name: POSTGRES-USER
              alias: POSTGRES_USER
            - name: POSTGRES-PASS
              alias: POSTGRES_PASS
            - name: POSTGRES-HOST
              alias: POSTGRES_HOST
            - name: POSTGRES-PORT
              alias: POSTGRES_PORT
            - name: POSTGRES-DATABASE
              alias: POSTGRES_DATABASE
            - name: azure-tenant-id
              alias: AZURE_TENANT_ID
            - name: azure-client-secret
              alias: azure-client-secret
            - name: azure-app-id
              alias: AZURE_AUDIENCE_ID
            - name: CSDS-KEY-1
              alias: CSDS_KEY_1
            - name: CSDS-KEY-2
              alias: CSDS_KEY_2
