apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: appreg-api
  namespace: appreg
spec:
  releaseName: appreg-api
  values:
    java:
      ingressHost: appreg-api.perftest.platform.hmcts.net
      image: hmctsprod.azurecr.io/appreg/api:prod-a8c9a2a-20260715100130 # {"$imagepolicy": "flux-system:appreg-api"}
      environment:
        ENV_NAME: "PERFTEST"
        LOG_LEVEL: "DEBUG"
