apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../cath-web/cath-web.yaml
  - ../../cath-api/cath-api.yaml
  - ../../cath-crons/cath-crons.yaml
  - ../../cath-postgres/cath-postgres.yaml
  - ../../../base/slack-provider/prod
namespace: cath
patches:
  - path: ../../identity/prod.yaml
  - path: ../../cath-web/prod.yaml
  - path: ../../cath-api/prod.yaml
  - path: ../../cath-crons/prod.yaml
  - path: ../../cath-postgres/prod.yaml
  - path: ../../serviceaccount/prod.yaml
