apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-web
spec:
  releaseName: cath-web
  values:
    nodejs:
      image: hmctspublic.azurecr.io/cath/cath-web:prod-latest # {"$imagepolicy": "flux-system:cath-web"}
      disableTraefikTls: true
  chart:
    spec:
      chart: ./stable/cath-web
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 5m
  install:
    disableWait: true
  upgrade:
    disableWait: true
