apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-web
  namespace: cath
spec:
  releaseName: cath-web
  values:
    nodejs:
      ingressHost: cath-web.staging.platform.hmcts.net
      environment:
        BASE_URL: https://cath-web.staging.platform.hmcts.net
        ENABLE_TEST_SUPPORT: "true"
