apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pre-api-cron-cleanup-b2c-alternative-emails
  namespace: pre
spec:
  values:
    global:
      jobKind: CronJob
    job:
      suspend: false
      schedule: "0 20 * * *"
      image: hmctsprod.azurecr.io/pre/api:staging-c9770fd-20260427140842 # {"$imagepolicy": "flux-system:stg-pre-api"}
      environment:
        PLATFORM_ENV_TAG: Staging
