apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pre-api-cron-perform-re-encode-requests
  namespace: pre
spec:
  values:
    global:
      jobKind: CronJob
    job:
      suspend: false
      disableActiveClusterCheck: true
      schedule: "2-59/5 * * * *" # every 5 mins, offset from regular edit processing
      image: hmctsprod.azurecr.io/pre/api:prod-1b879b3-20260514085957 # {"$imagepolicy": "flux-system:pre-api"}
      environment:
        PLATFORM_ENV_TAG: Production
        PORTAL_URL: https://portal.pre-recorded-evidence.justice.gov.uk/
        ENABLE_NEW_EMAIL_SERVICE: true
