apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pre-api-cron-perform-re-encode-requests
  namespace: pre
spec:
  values:
    global:
      jobKind: CronJob
    job:
      suspend: false
      disableActiveClusterCheck: true
      schedule: "2-59/5 0-4,18-23 * * 0-4" # every 5 mins, offset by 2 minutes between 6pm UTC and 5am UTC
      image: hmctsprod.azurecr.io/pre/api:prod-510db7f-20260617111051 # {"$imagepolicy": "flux-system:pre-api"}
      environment:
        PLATFORM_ENV_TAG: Production
        PORTAL_URL: https://portal.pre-recorded-evidence.justice.gov.uk/
        ENABLE_NEW_EMAIL_SERVICE: true
