apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: demo-courtfines-app
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  imageRepositoryRef:
    name: courtfines-app
  filterTags:
    pattern: "^pr-236-[a-f0-9]+-(?P<ts>[0-9]+)$"
    extract: "$ts"
  policy:
    alphabetical:
      order: asc
