apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: courtfines-app
  namespace: courtfines
spec:
  releaseName: courtfines-app
  values:
    nodejs:
      ingressHost: courtfines-app.ithc.platform.hmcts.net
      image: hmctsprod.azurecr.io/courtfines/app:prod-3dc2e21-20260817073126 # {"$imagepolicy": "flux-system:courtfines-app"}
      environment:
        ENV_NAME: "ITHC"
        LOG_LEVEL: "DEBUG"
