apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: courtfines-app
  namespace: courtfines
spec:
  releaseName: courtfines-app
  values:
    nodejs:
      ingressHost: courtfines.justice.gov.uk
      image: hmctsprod.azurecr.io/courtfines/app:prod-6edf805-20260724080710 # {"$imagepolicy": "flux-system:courtfines-app"}
      environment:
        ENV_NAME: "PRODUCTION"
        LOG_LEVEL: "INFO"
