apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: courtfines-app
  namespace: courtfines
spec:
  releaseName: courtfines-app
  values:
    nodejs:
      ingressHost: courtfines.justice.gov.uk
      image: hmctsprod.azurecr.io/courtfines/app:prod-7338bae-20260915130223 # {"$imagepolicy": "flux-system:courtfines-app"}
      environment:
        ENV_NAME: "PRODUCTION"
        LOG_LEVEL: "INFO"
        MAINTENANCE_BANNER_ENABLED: "true"
        MAINTENANCE_BANNER_MESSAGE: "HMCTS advise you not to attempt any payments between 1:30am and 5:30am on Monday 5 October 2026. Payments may fail during this time because of Barclaycard essential maintenance."
        PAYMENTS_PAUSED: "false"
