apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: courtfines-app
  namespace: courtfines
spec:
  releaseName: courtfines-app
  values:
    nodejs:
      ingressHost: courtfines-app.staging.platform.hmcts.net
      image: hmctsprod.azurecr.io/courtfines/app:prod-ba0fbc2-20260813075346 # {"$imagepolicy": "flux-system:courtfines-app"}
      environment:
        ENV_NAME: "STAGING"
        LOG_LEVEL: "DEBUG"
        MAINTENANCE_BANNER_ENABLED: "true"
        MAINTENANCE_BANNER_MESSAGE: "The HMCTS Online payments service will be unavailable from 10pm on Friday 7 August to 8am on Saturday 8 August for an essential upgrade."
        PAYMENTS_PAUSED: "false"
