apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base-no-api-token
  - ../../base
  - ../../identity/apple-azure-identity.yaml
  - ../../../azureserviceoperator-system/resources/resource-group.yaml
  - ../aso/sscs-postgres.yaml
  - ../../../azureserviceoperator-system/resources/flexibleserver-postgres-config.yaml
namespace: toffee
patches:
  - path: ../../identity/sbox.yaml
  - path: ../../frontend/sbox.yaml
  - path: ../../recipe-backend/sbox.yaml
  - path: ../../recipe-receiver/sbox.yaml
  - path: workload-identity.yaml
  - path: ../../serviceaccount/sbox.yaml
