apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base-no-api-token
  - ../../base
  - ../../identity/apple-azure-identity.yaml
  - ../../../azureserviceoperator-system/resources/resource-group.yaml
  - ../../../azureserviceoperator-system/resources/flexibleserver-postgres.yaml
  - ../../../azureserviceoperator-system/resources/flexibleserver-postgres-config.yaml
  - ../sops-secrets
namespace: toffee
patches:
  - path: ../aso/toffee-postgres.yaml
  - target:
      group: dbforpostgresql.azure.com
      version: v1api20230601preview
      kind: FlexibleServer
    patch: |-
      - op: replace
        path: /apiVersion
        value: dbforpostgresql.azure.com/v20250801
  - path: ../../identity/sbox.yaml
  - path: ../../frontend/sbox.yaml
  - path: ../../recipe-backend/sbox.yaml
  - path: ../../recipe-receiver/sbox.yaml
  - path: workload-identity.yaml
  - path: ../../serviceaccount/sbox.yaml
