apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: admin
spec:
  releaseName: external-dns
  values:
    domainFilters:
      - sbox.platform.hmcts.net