apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-api
spec:
  releaseName: cath-api
  values:
    nodejs:
      replicas: 2
      ingressHost: cath-api.platform.hmcts.net
      environment:
        REDIS_HOST: cath-prod.redis.cache.windows.net
      keyVaults:
        pip-ss-kv:
          secrets:
            - name: app-tenant-id
              alias: AZURE_TENANT_ID
            - name: app-pip-data-management-id
              alias: AZURE_CLIENT_ID
            - name: app-pip-data-management-scope
              alias: AZURE_SCOPE
            - name: redis-access-key
            - name: app-insights-connection-string
            - name: postgres-url
              alias: DATABASE_URL
      autoscaling:
        enabled: true
        cpu:
          enabled: true
          averageUtilization: 70
        memory:
          enabled: false
