apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-api
  namespace: cath
spec:
  releaseName: cath-api
  values:
    nodejs:
      ingressHost: cath-api.staging.platform.hmcts.net
      environment:
        ENABLE_TEST_SUPPORT: "true"

