apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-user-service
  namespace: opal
spec:
  releaseName: opal-user-service
  values:
    java:
      ingressHost: opal-user-service.demo.platform.hmcts.net
      image: hmctsprod.azurecr.io/opal/user-service:pr-551
      keyVaults:
        opal:
          secrets:
            - name: opal-CONSOLIDATED-POSTGRES-HOST
              alias: OPAL_USER_DB_HOST
            - name: opal-CONSOLIDATED-POSTGRES-PASS
              alias: OPAL_USER_DB_PASSWORD
            - name: opal-CONSOLIDATED-POSTGRES-PORT
              alias: OPAL_USER_DB_PORT
            - name: opal-CONSOLIDATED-POSTGRES-USER
              alias: OPAL_USER_DB_USERNAME
            - name: opal-CONSOLIDATED-POSTGRES-USER-DATABASE
              alias: OPAL_USER_DB_NAME
            - name: app-insights-connection-string
              alias: app-insights-connection-string
            - name: AzureADTenantId
              alias: AAD_TENANT_ID
            - name: AzureADClientId
              alias: AAD_CLIENT_ID
            - name: AzureADClientSecret
              alias: AAD_CLIENT_SECRET
            - name: OpalTestUserPassword
              alias: OPAL_TEST_USER_PASSWORD
            - name: role-mapping-storage-container-name
              alias: ROLE_MAPPING_STORAGE_CONTAINER_NAME
            - name: storage-connection-string
              alias: AZURE_STORAGE_CONNECTION_STRING
            - name: storage-account-name
              alias: AZURE_STORAGE_ACCOUNT_NAME
            - name: redis-connection-string
              alias: REDIS_CONNECTION_STRING
      environment:
        DUMMY_VAR: 0
        OPAL_FRONTEND_URL: https://opal-frontend.demo.apps.hmcts.net
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/demo
