apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-user-service
  namespace: opal
spec:
  releaseName: opal-user-service
  values:
    java:
      autoscaling:
        enabled: true
      image: hmctsprod.azurecr.io/opal/user-service:pr-614-2c6e333-20260721103301 # {"$imagepolicy": "flux-system:opal-user-service-pr"}
      ingressHost: opal-user-service.test.platform.hmcts.net
      environment:
        DUMMY_VAR: 1
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/perfTest
