apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal-user-service
  namespace: opal
spec:
  releaseName: opal-user-service
  values:
    java:
      image: hmctsprod.azurecr.io/opal/user-service:pr-xxxx-80d1e57-20260609171955 # {"$imagepolicy": "flux-system:test-opal-user-service"}
      ingressHost: opal-user-service.test.platform.hmcts.net
      environment:
        DUMMY_VAR: 1
        OPAL_FRONTEND_URL: https://opal-frontend.test.apps.hmcts.net
        FLYWAY_LOCATIONS: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/perfTest
