apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pip-publication-services
  namespace: pip
spec:
  releaseName: pip-publication-services
  values:
    java:
      image: hmctsprod.azurecr.io/pip/publication-services:pr-568-86195f4-20260323161747
      keyVaults:
        pip-ss-kv:
          resourceGroup: pip-ss-test-rg
          secrets:
            - name: gov-uk-notify-test-api-key
              alias: NOTIFY_API_KEY
            - name: app-pip-publication-services-id
              alias: CLIENT_ID
            - name: app-pip-publication-services-pwd
              alias: CLIENT_SECRET
            - name: app-tenant-id
              alias: TENANT_ID
            - name: app-pip-publication-services-scope
              alias: APP_URI
            - name: app-pip-data-management-scope
              alias: DATA_MANAGEMENT_AZ_API
            - name: app-pip-account-management-scope
              alias: ACCOUNT_MANAGEMENT_AZ_API
            - name: pip-team-email
              alias: PI_TEAM_EMAIL
            - name: courtel-certificate
              alias: THIRD_PARTY_CERTIFICATE
            - name: app-insights-java-connection-string
              alias: APP_INSIGHTS_CONNECTION_STRING
            - name: REDIS-V6-HOST
              alias: REDIS_HOST
            - name: REDIS-V6-PORT
              alias: REDIS_PORT
            - name: REDIS-V6-PASSWORD
              alias: REDIS_PASSWORD
            - name: xhibit-s3-access-key
              alias: XHIBIT_S3_ACCESS_KEY
            - name: xhibit-s3-access-key-secret
              alias: XHIBIT_S3_SECRET_KEY
            - name: cath-mi-client-id
              alias: MANAGED_IDENTITY_CLIENT_ID
      replicas: 2
      ingressHost: pip-publication-services.test.platform.hmcts.net
      environment:
        DATA_MANAGEMENT_URL: https://pip-data-management.test.platform.hmcts.net
        ACCOUNT_MANAGEMENT_URL: https://pip-account-management.test.platform.hmcts.net
        NOTIFY_LINK_SUBSCRIPTION_PAGE: https://pip-frontend.test.platform.hmcts.net/subscription-management
        NOTIFY_CFT_SIGN_IN_LINK: https://pip-frontend.test.platform.hmcts.net/cft-login
        NOTIFY_LINK_AAD_RESET_PW_LINK_MEDIA: https://sign-in.pip-frontend.test.platform.hmcts.net/pip-frontend.test.platform.hmcts.net/oauth2/v2.0/authorize?p=B2C_1A_PASSWORD_RESET&client_id=7e6d47d3-ed02-4e32-a86c-7e01d74eb77a&nonce=defaultNonce&redirect_uri=https://pip-frontend.test.platform.hmcts.net/password-change-confirmation&scope=openid&response_type=code&prompt=login&response_mode=form_post
        NOTIFY_CRIME_SIGN_IN_LINK: https://pip-frontend.test.platform.hmcts.net/crime-login
        XHIBIT_S3_BUCKET_NAME: staging.xhibit.justice.gov.uk
        THIRD_PARTY_KEY_VAULT: pip-ss-tp-kv-test
      memoryRequests: 1200Mi
      autoscaling:
        enabled: true
        cpu:
          enabled: true
          averageUtilization: 70
        memory:
          enabled: false
